"""create mem

Revision ID: 926d74f2e73a
Revises: 
Create Date: 2022-06-19 06:00:32.420775

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '926d74f2e73a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mem',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('link', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mem')
    # ### end Alembic commands ###
