"""create skip of mem

Revision ID: fe5c1442eda4
Revises: 63d7382bb017
Create Date: 2022-06-19 09:35:35.686233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5c1442eda4'
down_revision = '63d7382bb017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skipofmem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mem_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mem_id'], ['mem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mem_id', 'user_id', name='_mem_user_skip_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skipofmem')
    # ### end Alembic commands ###
